-- 1. EMPLOYEE WHO DOES NOT HAVE A MANAGER.
select *
from EMPLOYEES
where manager_id is null;

-- 2. EMPLOYEES UNDER A MANAGER.
select *
from EMPLOYEES
where manager_id is not null;

-- 3. FIND ALL THE PHONE NUMBERS THAT CONTAIN 123.
select phone_number
from EMPLOYEES
where phone_number like '%123%';

-- 4. FIND ALL THE EMPLOYEES WHO DO NOT HAVE COMMISSION.
select *
from EMPLOYEES
where COMMISSION_PCT is null;

-- 5. HOW DO WE FIND OUT HOW MANY TABLES WE HAVE IN OUR DATABASE?
select count(*) as table_count
from user_tables;

-- 6. HOW DO WE DISPLAY ALL THE TABLE NAME OF THE DATABASE?
SELECT table_name FROM user_tables;

-- 7. WHAT IS THE QUERY TO FIND OUT ALL THE INFORMATION OF A SPECIFIC EMPLOYEE WHOSE EMPLOYEE_ID IS 107?
select * from EMPLOYEES
where EMPLOYEE_ID = 107;

-- 8. ROWNUM?

-- 9. WHAT IS THE QUERY TO FIND OUT EMPLOYEE_ID, FIRST_NAME,
--    LAST_NAME AND SALARY OF THOSE EMPLOYEES WHO HAVE EMPLOYEE_ID AS 100,101,102,103?
select employee_id, first_name, last_name, salary
from EMPLOYEES
where EMPLOYEE_ID between 100 and 103;

-- 10. HOW TO DISPLAY EMPLOYEE ID, FIRST NAME, LAST NAME AND SALARY OF A SPECIFIC EMPLOYEE
--     WHOSE FIRST NAME IS "PETER"?
select employee_id, first_name, last_name, salary
from EMPLOYEES
where FIRST_NAME = 'Peter';

-- 13. HOW TO DISPLAY ALL THE ATTRIBUTES OF FIELDS OF A TABLE? DESC EMPLOYEES;
DESC EMPLOYEES;

-- 14. HOW TO DISPLAY ALL THE CONTENTS OF A TABLE?
SELECT * FROM COUNTRIES;

-- 15. HOW TO DISPLAY EMPLOYEE_ID, FIRST_NAME, LAST_NAME AND SALARY FROM EMPLOYEE TABLE AND SORT BY EMPLOYEE_ID?
select employee_id, first_name, last_name, salary
from EMPLOYEES
order by EMPLOYEE_ID;

-- 17. HOW TO DISPLAY EMPLOYEE ID, FIRST NAME, LAST NAME AND SALARY OF A SPECIFIC EMPLOYEE
--     WHOSE FIRST NAME IS "PETER" AND LAST_NAME IS "TUCKER"?
select employee_id, first_name, last_name, salary
from EMPLOYEES
where FIRST_NAME = 'Peter' and last_name = 'Tucker';

-- 18. HOW TO FIND OUT THOSE EMPLOYEES WHOSE FIRST NAME START WITH CHARACTER 'P'?
select EMPLOYEE_id, first_name, last_name
from EMPLOYEES
where FIRST_NAME like 'P%';

-- 19. HOW TO FIND OUT THOSE EMPLOYEES WHOSE FIRST NAME ENDS WITH CHARACTER 'N'?
select EMPLOYEE_id, first_name, last_name
from EMPLOYEES
where FIRST_NAME like '%n';

-- 20. HOW TO FIND OUT THOSE EMPLOYEES WHOSE FIRST NAME START WITH CHARACTER 'P' AND FIRST NAME ENDS WITH CHARACTER 'M'
select EMPLOYEE_id, first_name, last_name
from EMPLOYEES
where FIRST_NAME like 'P%m';

-- 21. HOW TO FIND OUT THOSE EMPLOYEES WHOSE FIRST NAME START WITH CHARACTER 'N', 'A','P','K'?
select EMPLOYEE_id, first_name, last_name
from EMPLOYEES
where FIRST_NAME like 'N%'
  or first_name like 'A%'
  or first_name like 'P%'
  or first_name like 'K%'
order by FIRST_NAME;

-- 22. HOW TO FIND OUT EMPLOYEE_ID, FIRST NAME , LAST NAME AND SALARY?
select employee_id, first_name, last_name, salary
from EMPLOYEES;

-- 23. RENAME SALARY AS <MONTHLY SALARY>.
-- 24. HOW TO FIND OUT EMPLOYEE ID, FIRST NAME, LAST NAME AND SALARY AND COMMITION PCT OF ALL THE EMPLOYEES?
select employee_id, first_name, last_name, salary as "MONTHLY_SALARY", COMMISSION_PCT
from EMPLOYEES;

-------------------NULL, NOT NULL-----------------------------------------

-- 25. HOW TO FIND THOSE EMPLOYEES WHO HAVE COMMISION?
select * from EMPLOYEES
where COMMISSION_PCT is not null;

-- 26. HOW TO FIND WHOSE EMPLOYEES WHO DO NOT HAVE COMMISION.
select * from EMPLOYEES
where COMMISSION_PCT is null;

-- 27. HOW TO FIND OUT ALL THE AND EMPLOYEES WHO HAS COMMISION AND CALCULATE
--     THE TOTAL SALARIES AFTER ADDING THEIR COMMISION PERCENTAGE?
select
  EMPLOYEE_ID,
  FIRST_NAME,
  LAST_NAME ,
  salary + (salary * commission_pct) as TOTAL_SALARIES
from EMPLOYEES
where COMMISSION_PCT is not null;
--NOTE: SALARY AFTER COMMISSION = SALARY + SALARY* COMMISSION_PCT

-- 28. HOW TO FIND OUT EMPLOYEES MONTHLY AND YEARLY SALARY WITH COMMISSION?
select
  EMPLOYEE_ID,
  first_name,
  LAST_NAME,
  salary + (salary * commission_pct) as MONTHLY_SALARY,
  (salary + (salary * commission_pct)) * 12 as YEARLY_SALARY
from EMPLOYEES
where COMMISSION_PCT is not null;

-- 29. HOW TO FIND OUT EMPLOYEES MONTHLY AND YEARLY SALARY WITH COMMISSION? AND THE HIGHEST YEARLY SALARY WITH COMMISSION?
select
  EMPLOYEE_ID,
  first_name,
  LAST_NAME,
  salary + (salary * commission_pct) as MONTHLY_SALARY,
  (salary + (salary * commission_pct)) * 12 as YEARLY_SALARY
from EMPLOYEES
where COMMISSION_PCT is not null
  and rownum = 1
order by YEARLY_SALARY;

-- 30. HOW TO FIND OUT EMPLOYEES MONTHLY AND YEARLY SALARY WITH COMMISSION? AND THE HIGHEST  AND LOWEST YEARLY SALARY WITH COMMISSION?

-- 31. HOW TO RETRIEVE THE FIRST 10 EMPLOYEE¡¯S INFORMATION?

-- 32. HOW TO RETRIEVE LAST 10 EMPLOYEE¡¯S INFORMATION?

-- 33. HOW TO RETRIEVE 10TH TO 19TH EMPLOYEE_ID FIRST NAME, LAST NAME AND SALARY?


-- 34. HOW MANY EMPLOYEES WERE HIRED IN LAST 15 YEARS?

-- 35. HOW TO FIND OUT EMPLOYEE ID , FIRST NAME, LAST NAME, SALARY OF TOP TEN SALARY DRAWING EMPLOYEES?

-- 36. HOW TO FIND OUT THOSE EMPLOYEES WHO EARN MAXIMUM SALARY?

-- 37. FIND THE MINIMUM SALARY AND MAXIMUM SALARY OF EMPLOYEE.

-- 38. HOW TO FIND OUT THOSE EMPLOYEES WHO EARN MORE THAN AVERAGE SALARY?

-- 39. HOW TO FIND OUT THOSE EMPLOYEES WHO EARN MINIMUM SALARY?

-- 40. HOW TO FIND OUT THOSE EMPLOYEES WHO EARN SAME SALARY AS ¡¯NEENA¡¯?

------- JOIN---------

-- 41. HOW TO FIND OUT EMPLOYEE FIRST, LAST NAME, SALARY, DEPARTMENT ID AND DEPARTMENT NAME?(TWO TABLE)

-- 42. HOW TO FIND OUT EMPLOYEE FIRST NAME, LAST NAME, SALARY, DEPARTMENT ID, DEPARTMENT NAME, AND COUNTRY NAME?(FOUR TABLES)

-- 43. HOW TO FIND OUT EMPLOYEE FIRST, LAST NAME, SALARY DEPARTMENT ID, DEPARTMENT NAME, COUNTRY NAME, AND REGION NAME?(FIVE TABLE)

-- 44. HOW TO FIND OUT ONLY THOSE EMPLOYEES WHO ARE ASSOCIATED WITH ANY DEPARTMENT?

-- 45. HOW TO FIND OUT ALL EMPLOYEES WHO ARE ASSOCIATED WITH ANY DEPARTMENTS OR NOT?

-- RIGHT OUTER JOIN ----
-- 46. HOW TO FIND ALL DEPARTMENTS WHICH HAVE EMPLOYEES INCLUDING THE DEPARTMENT THAT DO NOT HAVE EMPLOYEES?, (MATCHING & NON-MATCHING)
-- 47. HOW TO FIND OUT THE DEPARTMENTS THAT DO NOT HAVE ANY EMPLOYEES?

-- 48. HOW TO FIND OUT EMPLOYEES THAT DO NOT BELONG TO ANY DEPARTMENTS?

-- 49. HOW TO FIND OUT THOSE MANAGERS WHO MANAGE ONLY ONE EMPLOYEE?


-- 34. HOW MANY EMPLOYEES WERE HIRED IN LAST 15 YEARS?
select count(*) -- or count(*)
from employees
where hire_date >= '01-JAN-2008'; -- oracle data format dd-MMM-yyyy
-- or you can use TO_DATE() to format the date in any pattern that you want like example below
-- where hire_date >= TO_DATE('2008-01-01','YYYY-MM-DD');
